CREATE OR REPLACE TRIGGER TRG_INS_CASE
AFTER INSERT ON PATIENT FOR EACH ROW
BEGIN
INSERT INTO CASE VALUES (SEQUENCE_PRIMARY_ID.NEXTVAL,'NEW',:NEW.PATIENT_ID,SYSDATE,SYSDATE,NULL,NULL);
END;
/

CREATE OR REPLACE TRIGGER TRG_UPD_CASE
AFTER UPDATE ON PATIENT FOR EACH ROW
BEGIN
INSERT INTO CASE VALUES (SEQUENCE_PRIMARY_ID.NEXTVAL,'Re-visit',:NEW.PATIENT_ID,SYSDATE,SYSDATE,NULL,NULL);
END;
/